# Generated by Django 4.0.2 on 2022-03-15 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0004_rename_price_paymentgateway_payment_price_and_more'),
        ('order', '0014_remove_order_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_ids', to='order.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='Payment.paymentgateway')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_status', to='Payment.paymentgateway')),
                ('total_amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_amount', to='order.order')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
