# Generated by Django 4.0.2 on 2022-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_amount',
            field=models.FloatField(default=0),
        ),
    ]
