# Generated by Django 4.0.2 on 2022-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Created', 'created'), ('Paid', 'paid'), ('Shipped', 'shipped'), ('Refunded', 'refunded'), ('Cancelled', 'cancelled')], max_length=20, null=True),
        ),
    ]
