# Generated by Django 4.0.2 on 2022-03-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_created_by_orderitem_user_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_by',
            new_name='user',
        ),
    ]
