# Generated by Django 4.0.2 on 2022-03-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_total_price_alter_orderitem_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_charges',
        ),
    ]
