# Generated by Django 4.0.2 on 2022-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_shipping_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(choices=[('Created', 'created'), ('Paid', 'paid'), ('Shipped', 'shipped'), ('Refunded', 'refunded'), ('Cancelled', 'cancelled')]),
        ),
    ]
