# Generated by Django 4.0.2 on 2022-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(choices=[('Created', 'created'), ('Paid', 'paid'), ('Shipped', 'shipped'), ('Refunded', 'refunded'), ('Cancelled', 'cancelled')], default=False),
        ),
    ]
