# Generated by Django 4.0.2 on 2022-03-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
    ]
