# Generated by Django 4.0.2 on 2022-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_quantity_alter_storeowner_user_delete_cart'),
        ('cart', '0003_remove_cart_created_remove_cart_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='myapp.Product'),
        ),
    ]
