# Generated by Django 4.0.2 on 2022-02-28 06:41

import coupon.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(default=False, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only uppercase letters & numbers are allowed.')])),
                ('start_date', models.DateTimeField(validators=[coupon.models.Coupon.star_date])),
                ('expire_date', models.DateTimeField(validators=[coupon.models.Coupon.end_date])),
                ('max_limit', models.PositiveIntegerField(default=2, help_text='How Many Times Used this coupon')),
                ('per_user', models.PositiveIntegerField(default=2, help_text='How often user used this Coupon')),
                ('discount_type', models.CharField(blank=True, choices=[('P', 'percentage'), ('F', 'flat')], max_length=10, null=True)),
                ('discount_amount', models.PositiveIntegerField(default=1, help_text='what is customer discount')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
