# Generated by Django 4.0.2 on 2022-02-24 12:10

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(validators=[coupon.models.Coupon.start_date]),
        ),
    ]
