# Generated by Django 4.0.2 on 2022-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_coupon_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
