# Generated by Django 4.0.2 on 2022-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Gir_Somnath', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='Kodinar', max_length=50),
        ),
    ]
