# Generated by Django 4.0.2 on 2022-02-11 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_forgot_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_id', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('', ''), ('Ahemdabad', 'ahemdabad'), ('Gandhinagar', 'gandhinagar'), ('Baroda', 'baroda'), ('Surat', 'surat'), ('Delhi', 'delhi'), ('Rajkot', 'rajkot'), ('Bhavnagar', 'bhavnagar'), ('Mumbai', 'mumbai'), ('Somnath', 'Somnath')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
