# Generated by Django 4.0.2 on 2022-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_storeowner_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='store_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
