# Generated by Django 4.0.2 on 2022-02-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_image_product_product_image_product_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='flat', max_length=20)),
                ('discount_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.storeowner'),
        ),
    ]
