# Generated by Django 4.0.2 on 2022-02-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_discount_alter_product_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.discount'),
        ),
    ]
