# Generated by Django 4.0.2 on 2022-02-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeowner',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
