# Generated by Django 4.0.2 on 2022-02-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_quantity_alter_storeowner_user_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_id',
        ),
    ]
