# Generated by Django 4.0.2 on 2022-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_product_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeowner',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
