# Generated by Django 4.0.2 on 2022-03-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_storeowner_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
