# Generated by Django 4.0.2 on 2022-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Fail', 'fail'), ('Processing', 'processing'), ('Complete', 'complete'), ('Onhold', 'onhold')], max_length=20, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
