# Generated by Django 4.0.2 on 2022-02-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
        ('cart', '0003_alter_cartitem_total_price'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgetway',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymentgetway',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='paymentgetway',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='paymentgetway',
            name='status',
            field=models.CharField(blank=True, choices=[('Fail', 'fail'), ('Processing', 'processing'), ('Complete', 'complete'), ('Onhold', 'onhold')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentgetway',
            name='transection_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
