# Generated by Django 4.0.2 on 2022-03-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentgateway',
            old_name='transection_id',
            new_name='transaction_id',
        ),
    ]
