# Generated by Django 4.0.2 on 2022-03-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_remove_paymentgetway_payment_paymentgetway_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgetway',
            name='cart',
        ),
    ]
