# Generated by Django 4.0.2 on 2022-03-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem'),
        ('Payment', '0003_remove_paymentgetway_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Fail', 'fail'), ('Processing', 'processing'), ('Complete', 'complete'), ('Onhold', 'onhold')], max_length=20, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentGetway',
        ),
    ]
