# Generated by Django 4.0.2 on 2022-03-15 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0014_remove_order_updated_by'),
        ('Payment', '0003_rename_transection_id_paymentgateway_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentgateway',
            old_name='price',
            new_name='payment_price',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Case on delivery'), ('Stripe', 'Stripe')], default='Stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_payment', to='order.order'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='status',
            field=models.CharField(blank=True, choices=[('Fail', 'Fail'), ('Processing', 'Processing'), ('Draft', 'Draft'), ('Done', 'Done')], max_length=20, null=True),
        ),
    ]
