# Generated by Django 4.0.2 on 2022-02-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
