# Generated by Django 4.0.2 on 2022-02-22 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cart_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0004_alter_address_city_alter_address_country_and_more'),
        ('checkout', '0002_remove_checkout_address_remove_checkout_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
